.circleci/config.yml, .dockerignore, .gitignore, Dockerfile.build, Dockerfile.export, docker-build.sh, orbs-network.go
=> Basic build

acceptance/consensus.go, bootstrap/node.go, consensus/consensus_algo.go, loopcontrol/loop_control.go, publicapi/public_api.go, testharness/network.go
for fine-grained control of ticks in a background task loop
consensus.go test exemplifies usage
=> introduced loop control mechanism

services/blockstorage/service.go, services/blockstorage/test/commit_block.go, services/blockstorage/test/component_test.go, services/consensusalgo/leanhelix/service.go, services/gossip/service.go, services/gossip/transport_listener.go, test/blocks.go
Finished the flow except for:
```
If any of the intra block syncs (StateStorage, TransactionPool) is blocking and waiting, wake it up.
```
=> Commit Block flow

bootstrap/node.go, config/hardcoded_config.go, services/blockstorage/adapter/leveldb_persistence.go, services/blockstorage/test/harness.go, services/consensusalgo/benchmarkconsensus/test/harness.go, test/harness/network.go, test/harness/services/blockstorage/adapter/memory_persistence.go
=> split hard coded config into mixable structs

crypto/bloom/timestamp_test.go, crypto/digest/transactions_test.go, crypto/hash/hash_test.go, crypto/signature/ed25519_test.go
as part of pricing efforts, trying to create a convention for us to get a feel of time/cost of different operations we run, added some unit tests and benchmarks
=> crypto benchmark and unit tests

instrumentation/log/basic_logger_test.go, instrumentation/log/formatters.go, test.sh, test/acceptance/consensus_test.go, test/acceptance/simple_transfer_test.go, test/harness/network.go, test/harness/report_test_id.go
=> Add uid for every acceptance test run

instrumentation/log/basic_logger.go, instrumentation/log/basic_logger_test.go, instrumentation/log/formatters.go
=> logger bug fixes

instrumentation/log/basic_logger.go, instrumentation/log/basic_logger_test.go
This function allows you to log a diff between 2 fields.
Can provide the base to fix #57
=> Add LogFailedExpectation

synchronization/block_tracker.go, synchronization/block_tracker_test.go
This is an attempt to remove all test related code from production code of BlockTracker.
This is work in progress, PR is opened to get review.
The first commit moves the implementation of the test related logic from BlockTracker to unit tests, and leaves a minimal footprint inside production code in the form of a private callback function member - used by unit tests alone.
This is cleaner than before but we still have a member in production code. 
A major disadvantage is that it leaves the unit test code more complicated than it should be.
The main advantage of this implementation is that it keeps the tests as fast as possible. we don't waste any time on waiting or sleeping.
An alternative solution was proposed by @talkol  
Tal suggested to use test.Consistently() and test.Eventually() …
=> Block Tracker - refactor unit tests

test/harness/services/gossip/adapter/tampering_transport.go
=> Guarding tampering transport listener map with mutex

services/transactionpool/add_new_transaction.go, services/transactionpool/pools.go, services/transactionpool/test/add_transaction_test.go, services/transactionpool/validate_transaction.go, services/transactionpool/validate_transaction_test.go
=> receipt from add new transaction is now never nil

Dockerfile.build, build-binaries.sh
Fixes a bug that prevented the compilation of devtools.
=> More debug tools for docker builder

services/blockstorage/block_sync.go, services/blockstorage/block_sync_test.go
=> Do not respond to sync requests that are not relevant

README.md
=> Update docs regarding docker debug mode and docker in general

services/transactionpool/cleaner_test.go
=> attempting to fix flakyness by increasing interval to 1ms

crypto/digest/transactions_test.go, devtools/jsonapi/main/main.go, devtools/sambusac/test/sambusac_test.go, services/consensuscontext/test/harness.go, services/processor/native/repository/BenchmarkToken/contract.go, services/processor/native/test/benchmark_contract_test.go, services/processor/native/test/benchmark_token_test.go, services/processor/native/test/call_permission_test.go, services/processor/native/test/contract_existence_test.go, services/processor/native/test/harness.go, services/transactionpool/test/get_transactions_for_ordering_test.go, test/acceptance/consensus_test.go, test/acceptance/simple_transfer_test.go, test/acceptance/stress_test.go, test/builders/address.go, test/builders/blocks.go, test/builders/transactions.go, test/e2e/deploy_native_test.go, test/e2e/multiple_transaction_test.go, test/harness/network.go
and fixed all tests in the system accordingly
=> Added accounts (addresses) to BenchmarkToken

.circleci/config.yml, Dockerfile.acceptance, docker-compose.acceptance.yml, docker-test.acceptance.sh, test.common.sh
=> Save acceptance logs in case of failure

config/factory.go
I suspect these are unused and shouldn't be here. How they got here is a mystery I'm too lazy to pinpoint using git log :)
=> removed suspicious config values

services/consensusalgo/benchmarkconsensus/leader.go
=> Close long living channel in benchmark consensus

bootstrap/httpserver/server.go, bootstrap/httpserver/server_test.go, devtools/gamma-server/test/gamma_server_and_cli_test.go, services/publicapi/basic_test.go, services/publicapi/get_transaction.go, services/publicapi/run_transaction.go, services/publicapi/send_transaction.go, services/publicapi/service.go, services/publicapi/test/get_transaction_test.go, services/publicapi/test/harness.go, services/publicapi/test/run_transaction_test.go, services/publicapi/test/send_transaction_test.go, test/builders/transactions.go, test/e2e/deploy_native_test.go, test/e2e/multiple_transaction_test.go, test/harness/network.go
Flesh out the call method
a bit code restructure 
make all the places that call method used wrongly work correctly
Kiril - please look that i didn't mess your meters
Tal/Eran - please look at e2e that i didn't mess
=> callMethod 

config/config.go, config/factory.go, config/file_config.go, config/hardcoded_config.go, services/blockstorage/block_sync.go, services/blockstorage/block_sync_test.go, services/blockstorage/service.go, services/blockstorage/test/block_sync_test.go, services/blockstorage/test/harness.go, services/consensuscontext/service.go, services/consensuscontext/test/harness.go, services/gossip/adapter/direct_transport.go, services/gossip/adapter/direct_transport_test_harness.go, services/publicapi/basic_test.go, services/publicapi/service.go, services/publicapi/test/harness.go, services/statestorage/service.go, services/statestorage/test/drivers.go, services/transactionpool/service.go, services/transactionpool/test/get_transaction_receipt_test.go, services/transactionpool/test/get_transactions_for_ordering_test.go, services/transactionpool/test/harness.go, test/harness/services/gossip/adapter/transport_contract_test.go
=> Hide default config, empty config and mutable config

services/blockstorage/service.go, services/blockstorage/test/commit_block_test.go
=> Refactor block already in storage check

config/array_flags.go, main.go
I have added that to help my ongoing effort to introduce management layer over node containers.
=> Support multiple config files

CONTRIBUTING.md, README.md
A place to log all our dev decisions (e.g. error handling) instead of jotting them on random Slack channels.
=> A very short stub of developer's notes

bootstrap/node_logic.go, instrumentation/log/basic_logger.go, instrumentation/metric/gauge.go, instrumentation/metric/gauge_test.go, instrumentation/metric/registry.go, services/blockstorage/service.go, services/blockstorage/test/harness.go
Also fixes a bug that erased metric name from periodic log.
=> Add blockHeight metric to block storage

synchronization/supervized/supervisor.go, synchronization/supervized/supervisor_test.go
=> fixed flakiness

services/blockstorage/service.go, test/context.go
=> fix ide issue for running all tests

test/harness/services/blockstorage/adapter/memory_persistence.go
there was a mutex in `InMemoryBlockPersistence` being used both for protecting the block slice AND the channels we're waiting for txs on. This PR separates them to two mutexes, hoping that a lock contention caused the flakiness in #399 
(hopefully) fixes #399
=> Attempting to fix race condition that flakes acceptance suites

devtools/gamma-server/test/gamma_server_and_cli_test.go, devtools/gammacli/commands/deploy.go, devtools/gammacli/commands/gen_keys.go, devtools/gammacli/commands/run.go, devtools/gammacli/commands/runner.go, devtools/gammacli/commands/start.go, devtools/gammacli/main/main.go, devtools/gammacli/server.go, synchronization/supervised/supervisor.go, test/development/deploy_native_test.go, test/harness/development_network.go
by compiling the cli to binary only once
=> Reduced gamma test duration significantly

.circleci/post-dashboard-link.py
=> Add error handling to github notification script

services/statestorage/test/_manual/stress_test.go
Added manual test for merkle init flow
=> New merkel init simulation test

config/file_config_test.go
=> Refactor file config tests

services/blockstorage/service.go
should not really solve the other issues we have with the fork
=> small fix for GetLastBlockHeight

lint.sh
Just install it locally (explained in the script) and run (explained in the script too).
=> Added lint.sh to run golangci-lint locally

test.sh
Merge this **only** after https://github.com/orbs-network/orbs-network-go/issues/379 is resolved!!!!!
=> Restore BlockStorage tests once issue 379 resolved

services/consensusalgo/benchmarkconsensus/common.go, services/consensusalgo/benchmarkconsensus/leader_test.go
The test is terrible, don't merge yet.
=> Fix required quorum size

test/acceptance/stress_test.go
This is an acceptance test we kinda forgot about - it tampers with the message binary data and currently fails. We need to investigate why it fails and make sure that it passes, as it kind of represents a case for a byzantine attacker
=> Acceptance tests corrupting gossip messages 

bootstrap/node.go, bootstrap/node_logic.go, services/statestorage/adapter/memory_persistence.go, services/statestorage/adapter/memory_persistence_test.go, services/statestorage/service.go, services/statestorage/test/drivers.go, test/harness/services/statestorage/adapter/memory_persistence.go
add nkeys and ncontracts for ss persistence
=> add read/write per second for statestorage.

bootstrap/inmemory/network.go, bootstrap/node_logic.go, config/config.go, config/factory.go, config/file_config_test.go, config/system_factory_presets.go, devtools/gammaserver/development_network.go, services/consensusalgo/benchmarkconsensus/leader.go, services/consensusalgo/benchmarkconsensus/test/harness.go, services/gossip/adapter/memory_transport.go, services/publicapi/send_transaction_test.go, services/publicapi/test/send_transaction_test.go, test/acceptance/quorum_size_test.go, test/e2e/deploy_native_test.go, test/e2e/harness.go, test/e2e/multiple_transaction_test.go, test/harness/acceptance_network.go, test/harness/contracts/benchmark_token.go, test/harness/network_builder.go, test/testify_extensions.go
fixes #477 
Starts a network with 4 out of 6 nodes up and configures for 66% required quorum size. Asserts a block can be closed.
=> Acceptance test asserting quorum size is taken into consideration

services/virtualmachine/deployment.go, services/virtualmachine/execution.go, services/virtualmachine/test/deployment_test.go, services/virtualmachine/test/double_deployment_test.go, services/virtualmachine/test/expectations.go, services/virtualmachine/test/harness.go, test/acceptance/stress_test.go
issue https://github.com/orbs-network/orbs-network-go/issues/490
=> fixed bug where two auto-deploying transactions in the same block were causing a double deploy

services/blockstorage/test/block_sync_stress_race_test.go
=> [WIP] attempting to fix flaky TestSyncPetitioner_Stress_CommitsDuringSync

instrumentation/log/filters.go, instrumentation/log/test_output.go
This saves memory, cpu and significant runtime in tests.
=> Using compiled regexps instead of compiling every log call

services/blockstorage/test/block_sync_full_flow_test.go, services/blockstorage/test/block_sync_stress_race_test.go
Attempting to solve issues in:
1. `TestSyncPetitioner_Stress_CommitsDuringSync`
1. `TestSyncPetitioner_CompleteSyncFlow`
=> [WIP] flakiness in inter node sync test

bootstrap/node_logic.go, services/crosschainconnector/ethereum/adapter/common.go, services/crosschainconnector/ethereum/adapter/report_connection_status.go, services/crosschainconnector/ethereum/adapter/report_connection_status_test.go, services/crosschainconnector/ethereum/adapter/simulator.go
=> refactored ethereum status checking to reduce log clutter

.circleci/config.yml, test.flakiness.sh
The nightly build assumes the npm package is installed globally which was not the case
this PR attempts to fix that.
=> fixing the bug with nightly complaining about missing package

bootstrap/inmemory/network.go, bootstrap/node.go, services/processor/native/adapter/native_compiler.go, services/processor/native/adapter/test/compiler_contract_test.go
=> added metrics to native compiler

config/system_factory_presets.go
addressing review comment from previous PR on current branch: PR merged before pushing final commit
=> reduce GOSSIP_RECONNECT_INTERVAL to 1 second

instrumentation/logfields/fields.go, instrumentation/logfields/fields_test.go, services/gossip/adapter/tcp/direct_incoming.go, services/gossip/topic_block_sync.go
=> added peer ip address into the gossip context

services/gossip/adapter/tcp/direct_harness.go, services/gossip/adapter/tcp/direct_incoming.go, services/gossip/adapter/tcp/direct_outgoing.go, services/gossip/adapter/tcp/direct_transport.go, services/gossip/adapter/tcp/direct_transport_test.go, services/gossip/adapter/test/transport_contract_test.go
=> Removed random port from tcp transport tests

.gitignore, test/acceptance/network_harness_builder.go
=> Reducing acceptance test timeout

bootstrap/node.go, bootstrap/node_logic.go, config/version.go, instrumentation/metric/config.go
=> moved version metric registration to NodeLogic so that it also works in Gamma

config/config.go, config/factory.go, config/system_factory_presets.go, test/e2e/network.go
Removed OverrideNodeSpecificValues from config to declutter E2E config creation
fixes #1149
=> removed OverrideNodeSpecificValues from config

bootstrap/gamma/deploy_native_test.go, bootstrap/gamma/gamma_e2e_test.go, bootstrap/gamma/gamma_test.go, bootstrap/gamma/main/main.go, bootstrap/gamma/server.go, bootstrap/gamma/simple_transfer_test.go, bootstrap/node.go, bootstrap/process.go, config/file_config_test.go, config/service_factory_presets.go, crypto/signature/ecdsa_secp256k1_test.go, services/consensusalgo/benchmarkconsensus/test/harness.go, services/gossip/adapter/tcp/direct_transport.go, services/gossip/adapter/testkit/tamperers.go, test/acceptance/ethereum_interop_test.go
Gamma E2E didn't actually run its `main()` func, opening us up for nasty bugs. This PR fixes this oversight,
Please only merge after merging # #1147, as this PR branch is forked from it.
=> Run Gamma's main in its e2e test

services/blockstorage/adapter/test/main/create_adapter_and_sleep_main.go
=> flakiness fix - extend sleep duration for advisory lock test

services/publicapi/test/get_block_test.go, services/publicapi/test/harness.go
A simple renaming to some internal variables, from commited to committed.
=> Fixed typo, from commited to committed

services/crosschainconnector/ethereum/adapter/rpc_connection.go
=> Redial Ethereum connection on every call, fixes #1160

services/processor/native/repository/_Elections/exports.go, services/processor/native/repository/_Elections/fix_rewards_and_stakes.go
Add two, one time only, functions to allow fixing rewards and fixing double delegation in state.
=> fix rewards & double delegate state.

.circleci/config.yml, .gitmodules
remove asb from network-go (both vendor and circle ci)
=> remove orbs-ethereum-contracts from network-go

.circleci/package-lock.json, .circleci/package.json
Fixes security warning related to shelljs.
=> Fetch nebula from master

Metrics.md, services/publicapi/run_query.go, services/publicapi/send_transaction.go, services/publicapi/service.go
=> More api metrics

config/system_factory_presets.go
=> Enable code sanitization for e2e

services/processor/native/sanitize_code.go
Turns out, safemath package was not whitelisted properly, and now our erc20 demo does not work.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
=> Update code sanitizer whitelist to include SDK/v1/safemath/*

services/transactionpool/test/get_transactions_for_ordering_test.go
Added two component tests to ensure transaction pool is not blocking when the context passed to getTransactionsForOrdering is cancelled.
These tests were introduced as part of an effort to fix concurrency issues in LeanHelix. The fix in LeanHelix includes relying on responsive behavior in Orbs when contexts get cancelled while go-routines are inside SPI calls.
Part of this PR includes tests for:
1. Verification that there is an acceptance test to ensure blocks are being closed after node-sync (`TestInterNodeBlockSync_WithBenchmarkConsensusBlocks`) 
1. `transactionpool.transactionWaiter.waitForIncomingTransaction` does not block when presented with a cancelled context (`TestTransactionWaiterReturnsWhenContextIsDone`)
=> added tests for non blocking behavior when TX pool receives a cancelled context

services/processor/native/call.go, services/processor/native/call_test.go, services/processor/native/test/call_argument_test.go
Prerequisite for #1225 
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
If this is a relatively large or complex change, kick off the discussion by explaining why you chose the solution you did and what alternatives you considered, etc...
=> Ellipsis in smart contracts

services/blockstorage/adapter/filesystem/file_system_persistence.go, services/blockstorage/adapter/filesystem/file_system_persistence_test.go
fixed the issue with the block storage metrics
@ronnno please verify its good now
=> fixed incorrect storage metrics

services/processor/native/repository/_Elections/exports.go, services/processor/native/repository/_Elections/fix_rewards_and_stakes8228900.go
add code to fix state after double delegation
=> fix bug new double delegation - election numbers

config/system_factory_presets.go
Fixes #1256 
Finally link to Lean Helix `master` branch.
=> PR 1256 Fix gamma config

services/processor/native/repository/_Elections/block_based_logic.go, services/processor/native/repository/_Elections/block_based_logic_test.go, services/processor/native/repository/_Elections/election_results.go, services/processor/native/repository/_Elections/election_results_test.go, services/processor/native/repository/_Elections/exports.go, services/processor/native/repository/_Elections/exports_unsafetests.go, services/processor/native/repository/_Elections/fix_first_elections.go, services/processor/native/repository/_Elections/guardians_test.go, services/processor/native/repository/_Elections/harness_test.go, services/processor/native/repository/_Elections/helpers.go, services/processor/native/repository/_Elections/helpers_test.go, services/processor/native/repository/_Elections/index.go, services/processor/native/repository/_Elections/mirror_delegate.go, services/processor/native/repository/_Elections/mirror_delegate_blockbased_test.go, services/processor/native/repository/_Elections/mirror_delegate_test.go, services/processor/native/repository/_Elections/processing_helpers.go, services/processor/native/repository/_Elections/processing_rewards.go, services/processor/native/repository/_Elections/processing_rewards_test.go, services/processor/native/repository/_Elections/processing_vote.go, services/processor/native/repository/_Elections/processing_vote_test.go
election contract updated to time based elections.
actual development was on orbs-ethereum-contracts
=> new time based election 

services/processor/native/repository/_Deployments/deploy.go
mini bug trigger was not auto deployed
=> add triggers to auto deploy

test/e2e/harness.go
This PR utilizes `client.CreateDeployTransaction` to support multiple files in contracts.
=> Update golang client sdk version

.github/PULL_REQUEST_TEMPLATE/blank.md, .github/PULL_REQUEST_TEMPLATE/breaking.md, .github/PULL_REQUEST_TEMPLATE/bugfix.md, .github/PULL_REQUEST_TEMPLATE/feature.md, .github/PULL_REQUEST_TEMPLATE/refactor.md
=> new PR templates

services/gossip/dispatcher.go
this was done while testing under load using this command:
> GOMAXPROCS=1 go test ./test/acceptance -run TestGazillionTxHappyFlow -count 200
=> increased buffer sizes for gossip topics

services/processor/native/sanitize_code.go
=> Allow experimental libraries import in contracts

docker/build/Dockerfile.export, docker/build/Dockerfile.gamma, services/processor/native/sanitize_code.go, test/contracts/whitelist/whitelist.go, test/e2e/deploy_native_test.go, test/e2e/deploy_native_whitelist_test.go
@noamoded please let me know about the list. Maybe we need to add more subpackages from from [golang.org/x/crypto](https://golang.org/x/crypto)?
=> Update contract whitelist with crypto packages

test/acceptance/node_sync_test.go, test/acceptance/service_sync_test.go
Ron fixed timing issues that alleviate these bugs:
fixes #412 
fixes #1286
=> clean up of "allow-errors" that are not needed

bootstrap/node.go, services/blockstorage/adapter/filesystem/block_writer.go, services/blockstorage/adapter/filesystem/file_system_persistence.go, services/blockstorage/adapter/test/contract_test.go, services/blockstorage/adapter/test/driver.go, services/gossip/adapter/transport.go, synchronization/supervised/shutdown.go
=> changed the way FileSystemBlockPersistence closes its block file

docker/build/Dockerfile.gamma
extend the fix in #1335  to `Dockerfile.gamma`
=> fixed gamma

go.mod, go.sum
Fixes https://github.com/orbs-network/lean-helix-go/issues/79
=> Updated lean-helix to v0.2.3

.circleci/config.yml, bootstrap/gamma/e2e/docker_based_e2e_test.go, bootstrap/gamma/ethereum/ethereum_finality_test.go, bootstrap/gamma/gamma_acceptance_test.go, bootstrap/gamma/harness.go, docker/test/docker-compose-gamma.yml, docker/test/gamma-e2e.sh, docker/test/ganache-related-test.sh
this is so that we do not release a gamma version that can't compile contracts
=> Added a test deploying a contract against a dockerized gamma

services/consensusalgo/leanhelixconsensus/service.go
=> Added missing onElection handler to Lean Helix Config

services/blockstorage/commit_block.go, services/blockstorage/init.go, services/blockstorage/test/commit_block_test.go
=> will now update node sync of committed block in a single goroutine

bootstrap/node_logic.go, instrumentation/trace/context.go, instrumentation/trace/context_test.go
This will make the node id of the node initiating a request appear in the request id.
=> Add node id to to context, tracing context and request id

services/gossip/service.go, services/gossip/topic_transaction_relay.go
=> Add metric for transaction relay errors.

.circleci/config.yml, .circleci/e2e-testnet.sh, .gitignore, bootstrap/gamma/e2e/docker_based_e2e_test.go, config/system_factory_presets.go
Due to the native compiler warmup compilation - the first transaction against Gamma takes a little more than 5 seconds sometimes and causes the Gamma E2E test to fail with status `NOT_EXECUTED` 
With this in mind - I've decided to increase the time we wait before we fail the test with a negative result to ensure the test can cope with the on-demand warmup compilation time.
=> Fix flakiness in gamma e2e deployment test

instrumentation/metric/gauge.go, instrumentation/metric/gauge_test.go, instrumentation/metric/histogram_export.go, instrumentation/metric/histogram_prometheus_test.go, instrumentation/metric/prometheus.go, instrumentation/metric/registry.go
=> ISSUE 1381: Prometheus metrics were not exported correctly

go.mod, go.sum
fixes #1390 
the race was already solved in Scribe v0.2.0 but we didn't upgrade to it
=> upgraded scribe to v0.2.1

instrumentation/metric/text.go, services/consensuscontext/committee.go, services/consensuscontext/service.go
TBD before this is completed:
Testing metrics?
Is this the right place to track?
Is this the right metric / format?
fix #1379
=> add committee members cound and IDs into metrics

docker/test/common-services.yml, docker/test/docker-compose.yml
It can be further generalised at the cost of convolution
fixes #1318
=> docker compose DRY refactor

test/eventually.go
=> add grace to `eventually` and `consistently` tests

.circleci/config.yml, .circleci/nightly.sh, .circleci/retry.sh
`go get -u github.com/orbs-network/go-junit-report` times out from time to time, retry 5 times
=> CircleCI retry script (used for go get go-junit-report)

services/processor/javascript/test/e2e/deploy_javascript_test.go
This test checks how the JS plugin handles panics/errors.
=> Update JS interop test

go.mod
dependency comes from Prometheus
=> added missing indirect dependency

services/transactionpool/adapter/clock.go
As per https://circleci.com/gh/orbs-network/orbs-network-go/22705?utm_campaign=vcs-integration-link&utm_medium=referral&utm_source=github-build-link
=> Fix race in clock.go

services/processor/native/repository/_Elections/mirror_delegate.go, services/processor/native/repository/_Elections/processing_vote.go
=> change %v to %x in _Elections

instrumentation/logger.go, main.go
log all panics on main
fixes #1473
=>  add bootstrap logger

services/gossip/adapter/tcp/outgoing_connection.go
Reverting #1484 - see there for reasoning.
"Add metrics for connection latency per node (requested by @gadcl)"
=> Revert PR 1484

go.mod, go.sum
=> upgraded testify to snapshot version

main.go
=> os.Exit(0) when running with --version

go.mod, go.sum, test/e2e/get_tx_status_test.go
Related to https://github.com/orbs-network/orbs-network-go/pull/1512 and https://github.com/orbs-network/orbs-client-sdk-go/pull/37
=> Update client sdk to v0.14.0

bootstrap/node_logic.go, go.mod
when system starts, only run a single consensus algo
=> only run a single consensus algo on node startup

go.mod, services/consensuscontext/call_contract_elected_validators.go, services/consensuscontext/call_contract_ordered_committee.go, services/virtualmachine/call_system.go, services/virtualmachine/test/call_system_contract_test.go, test/acceptance/callcontract/committee.go, test/acceptance/committee_reputation_test.go
In order to show that committee reputation is working in acceptance i found a bug in callsystemcontract.
=> acceptance test to prove reputation works. v1.

go.mod, go.sum, test/e2e/get_block_test.go
=> Update orbs-client-sdk-go to v0.15.0

services/virtualmachine/service.go, services/virtualmachine/test/process_query_test.go
=> Return error for queries with specific block height

README.md
=> Update README.md (fixes #1536)

config/system_factory_presets.go, services/management/adapter/file_provider.go, services/management/adapter/file_provider_test.go, services/management/adapter/memory_provider.go, services/management/adapter/memory_provider_test.go, services/management/management.go, services/management/management_test.go, test/acceptance/committee_election_test.go, test/acceptance/network.go, test/acceptance/network_harness.go
+ a bit of refactor
+ allow acceptance to verify mgmt update time if needed
=> add subscription and protocol to managememt

.circleci/release.sh
=> Do not publish hash version to Docker hub

services/management/adapter/_data/good.json, services/management/adapter/file_provider.go, services/processor/native/repository/_Elections/harness_test.go, services/processor/native/repository/_Elections/processing_vote.go, services/processor/native/repository/_Elections/processing_vote_test.go
=> Election change for no-balance, Weight for Mgmt

services/blockstorage/block_sync_server.go, services/blockstorage/test/block_sync_server_test.go, services/gossip/adapter/tcp/direct_transport_test.go, services/gossip/adapter/tcp/outgoing_connections.go, services/gossip/adapter/tcp/queue.go, services/gossip/topic_block_sync.go
=> Sync batch exceeds outgoing connection capacity 

docker/build/Dockerfile.export, entrypoint.sh
This PR aims to eliminate Boyar's knowledge of how the service runs
and introduces a new entrypoint which Boyar can call
=> adding the new boyar contract of how to run in v2

config/file_config.go, config/file_config_test.go
* zero values now override non zero defaults
* validation errors in complex types (address arrays etc) would not be detected and only partial parsing would be performed. now parsing fails with inner error reported
=> Config Parse issues

go.mod, go.sum, services/processor/native/repository/Committee/committee_test.go, services/processor/native/repository/Committee/reputation.go, services/processor/native/repository/Committee/update.go, services/processor/native/repository/Committee/update_test.go, services/processor/sdk/sdk_env.go, services/processor/sdk/sdk_env_test.go, services/virtualmachine/sdk_env.go, services/virtualmachine/test/harness.go, services/virtualmachine/test/sdk_env_test.go, test/acceptance/callcontract/committee.go, test/acceptance/committee_reputation_test.go
reputation contract : 
1) cap = 4, 
2) when next committee shows removal then clear reputation.
3) tests
SDK
1) add getNextBlockCommittee. 
2) make getnextblockcommittee and getblockproposer panic when singer not nil
3) tests
acceptance.
tamper a node, get it to have reputation 1, then change committee and show it is 0.
=> Reputation update for posv2

entrypoint.sh, instrumentation/logger.go
=> Output stdout logs as JSON and remove multilog timestamps from the log file

entrypoint.sh, test/e2e/deploy_native_test.go, test/e2e/deploy_native_whitelist_test.go
Added pre checks for logging folder being writable prior to starting up the application.
=> adding pre checks for logging in entry point

services/transactionpool/add_new_transaction.go, services/transactionpool/cleaner_test.go, services/transactionpool/cleanup.go, services/transactionpool/commit_transaction_receipts.go, services/transactionpool/init.go, services/transactionpool/service.go, test/acceptance/add_new_tx_test.go
added last committed block reference to pre-order check to facilitate the addition of new txs.
=> input last committed block refTime in preorder check

instrumentation/logger.go
`truncatingFileWriter` should not be used in production system. 
if `--log` is not specified the node should only write to stdout or http as required without writing to file. 
leaving support for `--log` flag only for tests if they need to preserve log files.
=> remove default file logger

config/config_system_presets.go
e2e and component change to lower.
=> reconnect 1 minute by default (= production)

entrypoint.sh
10 log files.
each log file is 16MB
=> Add more log files

bootstrap/httpserver/server_handlers_test.go, bootstrap/httpserver/status.go, instrumentation/metric/registry.go, services/blockstorage/adapter/filesystem/file_system_persistence.go
notifications status - added gauge init with value + used now as default for index init + fix status checks unix compare + added logging on status error
=> notifications status

bootstrap/httpserver/server_handlers_test.go, bootstrap/httpserver/status.go
if no genesis or genesis smaller than current reftime avoid checking the block storage ...
=> Consider genesisRef before generating status errors

bootstrap/node.go, config/config_system_presets.go, go.mod, services/management/adapter/file_provider.go, services/management/adapter/file_provider_test.go
change timeouts in config (30sec poll, 500mb filesize),
add timeout for the http get in the mgmt-file-provider
=> Mgmt url related small fixes

services/management/management.go
fix storage key caps after testing in private network situation
=> fix storage key caps after testing in private network situation
