orbs-network/orbs-network-go

test/acceptance/consensus.go, test/acceptance/simple_transfer.go, test/harness/services/gossip/adapter/tampering_predicates.go, test/harness/services/gossip/adapter/tampering_transport.go
tampering transport now uses message predicates, removing its intimare knowledge of message format
=> Introduced MessagePredicates to decouple message format from tampering transport

bootstrap/node.go, bootstrap/node_logic.go, instrumentation/reporting.go, services/blockstorage/service.go, services/blockstorage/test/commit_block.go, services/consensusalgo/leanhelix/service.go, test/acceptance/consensus.go, test/harness/network.go, test/harness/services/gossip/adapter/message_predicate_test.go, test/harness/services/gossip/adapter/mock_listener.go, test/harness/services/gossip/adapter/tampering_transport.go, test/harness/services/gossip/adapter/tampering_transport_test.go, test/harness/services/gossip/adapter/transport_contract_test.go
I was never happy with LoopControl (even though it's cool! :-) ) as it's not really in par with the concepts of black-box testing. Today I figured out we can achieve the same behavior with a latch on transport messages, waiting until at least one PRE_PREPARE message was sent, in the case of our consensus acceptance test.
Along the way, I also added some missing reporting messages in Block Storage
=> Replaced Loop Control with latch on gossip message types

crypto/address/address.go, crypto/address/address_test.go, crypto/base58/base58.go, crypto/base58/base58_test.go
- Base58 implementation (base on trezor code, refactored from c->go)
- Address struct according to the cryptosdk (lib) implementation, in native go
=> Base58 + Address crypto package

test/eventually.go, test/harness/services/gossip/adapter/mock_listener.go, test/harness/services/gossip/adapter/transport_contract_test.go
moved transport contract test to testify. Had to increase number of iterations in eventually, as Ginko's `Eventually` is apparently implemented differently and the memberlist transport took more than 100 ms to initialize properly.
=> moved transport contract test to testify

services/processor/native/repository/BenchmarkToken/contract.go, services/statestorage/adapter/memory_persistence.go, services/statestorage/adapter/memory_persistence_test.go
return zero value when reading from a non existent contract.
removes the need to initialize contract state explicitly
=> return zero value when reading from a non existent contract

devtools/jsonapi/main/main.go, devtools/sambusac/test/sambusac_test.go, services/consensuscontext/service.go, services/publicapi/service.go, services/transactionpool/add_new_transaction.go, services/transactionpool/commit_transaction_receipts.go, trace-transaction.sh
```
./trace-transaction.sh logs/node1.log 2c7ca5db3a414cca9e37f816e16f615d3e1d0dedf7381b753b6c87df9c710d04
info 2018-09-13T11:16:37.386319Z transaction received via public api node=dfc06c5be24a67adee80b35ab4f147bb1a35c55ff85eda69f40ef827bddec173 service=public-api flow=checkpoint txHash=2c7ca5db3a414cca9e37f816e16f615d3e1d0dedf7381b753b6c87df9c710d04
info 2018-09-13T11:16:37.386625Z adding new transaction to the pool node=dfc06c5be24a67adee80b35ab4f147bb1a35c55ff85eda69f40ef827bddec173 service=transaction-pool flow=checkpoint transaction={Transaction:{ProtocolVersion:1,VirtualChainId:2a,Timestamp:1553f1786b93560a,Signer:{Scheme:(Eddsa){NetworkType:NETWORK_TYPE_TEST_NET,SignerPublicKey:a8ce8303bb21a8f802957262dc1e37c56aa89378990ef7f91cab229e86060cf2,},},ContractName:BenchmarkToken,MethodNam …
```
=> Add ability to trace transactions

.circleci/archive-logs.sh, .circleci/config.yml, test.acceptance.sh, test.common.sh, test/acceptance/main_test.go, test/harness/acceptance_network.go
This PR drastically decreases memory usage of the acceptance suite, something that we initially believed was caused by a memory leak.
The actual problem was `go test` process capturing stdout and holding it in memory.
=> Log acceptance tests to files

bootstrap/httpserver/server.go, devtools/gamma-server/test/gamma_server_and_cli_test.go, test/e2e/harness.go
graceful now checks that time 0 no timeout + tests call with 0.
change ports so that there is less collision with gamma
(with Tal)
#309
=> change graceful shutdown to long + change ports

bootstrap/node_logic.go, instrumentation/metric/registry.go, instrumentation/metric/runtime.go
Reporting 3 new metrics:
> Runtime.HeapAlloc
> Runtime.HeapSys
> Runtime.GCCPUPercentage
The naming reflect namings of the `runtime.MemStats` object we read from.
Currently polling every 5 seconds, hard-coded
=> Added runtime metrics

test/debug.go, test/harness/network.go, test/harness/services/blockstorage/adapter/memory_persistence.go
When tests time out with panics that usually result from deadlocks, print goroutine stacks to help find what caused the deadlock
=> Debug deadlocks on acceptance timeouts

test.acceptance.sh, test/acceptance/cpunoise.go, test/cpunoise.go
add optional ongoing random bursts of cpu noise to make goroutine scheduling erratic in -count 100 flakiness tests
=> Improved flakiness -count 100 test by introducing cpu jitter

instrumentation/log/error_recording_logger.go, services/transactionpool/commit_transaction_receipts.go, test/acceptance/block_sync_test.go, test/acceptance/consensus_test.go, test/acceptance/deploy_native_test.go, test/acceptance/network_benchmark_test.go, test/acceptance/simple_transfer_test.go, test/acceptance/stress_test.go, test/harness/acceptance_network.go, test/harness/network.go, test/harness/network_builder.go, test/testify_extensions.go
Acceptance Suite will no longer allow errors not specifically marked as allowed. Any such error logged will fail the suite.
@jlevison I added some weird errors in block sync and storage as expected since they occur, but I can't explain them properly
=> Fail acceptance tests on unexpected errors

services/blockstorage/sync/block_sync.go, services/consensusalgo/benchmarkconsensus/service.go, services/consensusalgo/leanhelix/service.go, services/gossip/adapter/direct_transport.go, services/transactionpool/forward_transactions.go, synchronization/supervised/supervisor.go, synchronization/supervised/supervisor_test.go, synchronization/trigger.go, test/harness/contracts/api.go, test/harness/contracts/benchmark_token.go, test/harness/services/gossip/adapter/tampering_transport.go
- renamed `ShortLived` to `GoOnce` and `LongLived` to `GoForever`
- added test asserting that `GoForever` ends
- fixed `DirectTransport` to shut down when context ends
=> Simplified supervision

services/blockstorage/test/commit_block_test.go, services/blockstorage/test/get_block_headers_test.go, services/blockstorage/test/harness.go, services/statestorage/service.go, services/statestorage/test/get_state_hash_test.go, services/transactionpool/get_transactions_for_ordering.go, services/transactionpool/service.go, services/transactionpool/test/get_transactions_for_ordering_test.go, synchronization/block_tracker.go, synchronization/block_tracker_test.go, test/acceptance/consensus_test.go, test/acceptance/simple_transfer_test.go, test/acceptance/stress_test.go, test/harness/contracts/api.go, test/harness/contracts/benchmark_token.go, test/harness/network.go, test/harness/services/blockstorage/adapter/memory_persistence.go, test/harness/services/statestorage/adapter/memory_persistence.go
Changed block tracker's API to rely on context cancellation for timing out
This transfers responsibility for setting timeout for the caller, but it makes it more flexible and ensures that timeouts can be global for a specific use case or test.
It also enables sending timeouts from the client .
=> BlockTracker no longer takes timeout

test.common.sh
Print garbage collector statistics during nightly runs.
=> Add GC tracing to test.common.sh long-running tests

bootstrap/gamma/server.go, bootstrap/node_logic.go, instrumentation/metric/_manual_system_test.go, instrumentation/metric/registry.go, main.go, test/acceptance/network_harness_builder.go, test/acceptance/quorum_size_test.go, test/acceptance/service_sync_test.go, test/e2e/network.go
mute logging of system metrics to system logs:
monitoring (dashboard) now extracts the metrics directly via http polling, and not by extracting the metrics from the logs.
To make the logs more readable - muting automatic metrics logging.
=> remove logging of metrics to logs on interval

services/blockstorage/test/block_sync_stress_deadlock_test.go
potentially resolves #1121 
did not find the reason directly but found that the fake consensus go-routine keeps running and keeps the harness and mocks in memory after the test finishes.  it also causes cpu to be consumed.
While this does not explain the bug, since it's rarely reproduced, closing with this indirect fix.
=> stop fake consensus goroutine when context done

services/consensuscontext/validate_results_block_test.go
Minor additions to state diff `compare()`'s test function that @ronnno  and I added.
I branched it off `master` - as agreed on Slack we'll have a discussion on this.
=> Additions to Ron's test for compare() of state diffs

.gitmodules, bootstrap/node_logic.go, config/config.go, config/hardcoded_config.go, instrumentation/metric/ntp.go, instrumentation/metric/runtime.go
Improves monitoring. Partially addresses #1158 by introducing a metric that reports clock drift.
None
=> Add a metric to catch time drift; checks against NTP server

config/config.go, services/blockstorage/adapter/filesystem/codec.go, services/blockstorage/adapter/filesystem/file_system_persistence.go, services/blockstorage/adapter/test/detect_vchain_mismatch_test.go, services/blockstorage/adapter/test/driver.go, services/blockstorage/adapter/test/main/create_adapter_and_sleep_main.go
Validate `NETWORK_TYPE` configuration value matches the value found in blocks file header, on filesystem block storage adapter init. Fail loading if values do not match.
- [ x] Bugfix (non-breaking change which fixes an issue)
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. If you're unsure about any of them, don't hesitate to ask. We're here to help! This is simply a reminder of what we are going to look for before merging your code._
Currently network type is not in use. production configurations use the reserved value 0.
=> enforce network type field in blocks file header

services/blockstorage/adapter/memory/memory_persistence.go, services/blockstorage/adapter/test/contract_test.go, services/blockstorage/adapter/test/driver.go, services/blockstorage/block_queries.go, services/blockstorage/test/block_sync_full_flow_test.go, services/blockstorage/test/block_sync_server_test.go, services/blockstorage/test/block_sync_stress_deadlock_test.go, services/blockstorage/test/block_sync_stress_race_test.go, services/blockstorage/test/block_sync_test.go, services/blockstorage/test/commit_block_test.go, services/blockstorage/test/generate_proofs_test.go, services/blockstorage/test/harness.go, services/blockstorage/test/init_test.go, services/blockstorage/test/transaction_receipt_test.go, services/blockstorage/test/validation_test.go, test/builders/blocks.go
Addressing several `//TODO`s in block storage:
1. Structural block validations were moved to `ConsensusContext` service so no need for tests for these validations in BlockStorage
1. Removed redundant sanity checks in `GetBlockByTx`
1. Added contract tests for `GetTransactionReceipt`
1. Expanded component test for `GetTransactionReceipt`
1. Removed the need for confusing `.Reset()` calls on Block Storage test harness mock objects in several tests
1. Reinstated `TestBlockPersistenceContract_WriteOutOfOrderPast_FailsWhenBlockDifferent` as `TestBlockPersistenceContract_WriteOutOfOrder_PastBlocksIgnored`
1. Removed stale `//TODO`s
=> Tech Debt - Block Storage tests

services/blockstorage/adapter/filesystem/file_system_persistence.go, services/blockstorage/adapter/memory/memory_persistence.go, services/blockstorage/adapter/persistence.go, services/blockstorage/adapter/test/concurrency_test.go, services/blockstorage/adapter/test/contract_test.go, services/blockstorage/adapter/test/driver.go, services/blockstorage/adapter/test/persistence_test.go, services/blockstorage/adapter/testkit/tampering_persistence.go, services/blockstorage/commit_block.go, services/blockstorage/commit_block_test.go, services/blockstorage/test/commit_block_test.go
1. resolves #524
2. more consistent fork detection behavior. previously were open to race conditions which could prevent fork detection, now resolved.
3. comply with spec and check for forks for any attempt to write a block which already exists in storage - and not just for forks in the top persisted block
`BlockPersistence.WriteNextBlock()` now also returns the top persisted block height, and does not return an error if a future block is attempted. it merely returns false on the `added` param. the calling service later examines the result of the execution and executes the spec:
1. If the block was not `added` to persistent storage and the proposed block height is higher than the expected block height, the service now returns the error according to the spec. the adapter remains free of …
=> resolve issue 524

bootstrap/gamma/server.go, bootstrap/gamma/server_handlers.go, bootstrap/httpserver/server.go
This PR introduces an API call that shuts down Gamma.
This is a requirement from @gilamran so he can continue his work on Playground. Essentially, in case of shutdown a hard reset of individual gamma server will happen, but it will be automatically restarted by docker.
=> Shut down gamma with debug call

services/blockstorage/test/block_sync_server_test.go, services/blockstorage/test/harness.go
* resolves #329 
* Added harness function `verifyMocksConsistently` for cases where mocks are expected to `Never()` do something. This function should be called immediately after `verifyMocks` which has an `Eventually` type behavior to be tolerant for some delay before the mocks arrive at the first verified state. 
* minor syntactic changes to remove code warnings.
=> new test to for correct sync availability response 

test/e2e/block_storage_init_test.go, test/e2e/harness.go
Adding a skip on a test regarding block storage which is not suitable for running against remote networks where tampering of the block storage file isn't trivial
=> added a skip for the block storage test on remote networks

config/config.go, test/acceptance/network_harness.go, test/acceptance/network_harness_builder.go, test/acceptance/stress_benchmark_test.go, test/acceptance/stress_test.go
Adds two benchmarks (one baseline and one with ability to override current config values) for processing 1000 simple transactions.
Takes `3s` to complete with LH and `1s` to complete with benchmark.
If anyone wants to dig around looking for a low hanging fruit in regards to performance it's probably the best place to look.
=> Add TPS benchmark to acceptance test suite

.dockerignore, .gitmodules, docker/build/Dockerfile.export, docker/build/Dockerfile.export.experimental, docker/build/Dockerfile.gamma, docker/build/Dockerfile.gamma.experimental, docker/build/build.sh, services/processor/native/sanitize_code.go
Following conversation with @OdedWx and @erankirsh:
=> Add dependency on contract-external-libraries-go

services/transactionpool/forward_transactions_test.go
fix flaky bug in faulty signer because of interface change that was not represented.
=> fix missing ctx in faulty singer mock

services/gossip/adapter/tcp/direct_harness.go, services/gossip/adapter/tcp/direct_transport.go, services/gossip/adapter/tcp/direct_transport_test.go
Concurrency issue fixed by adding read locks around access to state members in `DirectTransport`
=> resolve #1232

services/crosschainconnector/ethereum/service.go, services/crosschainconnector/ethereum/test/config.go, services/crosschainconnector/ethereum/test/get_block_number_test.go, services/crosschainconnector/ethereum/test/harness.go
fix issue with getblocknumberbytime -> it should not used getfinality to find block number.
used the getbytimestamp
then just verifies that the found block is past finality.
=> fix bug. get block by time dont use getfinality 

test/acceptance/empty_block_time_test.go, test/acceptance/network_harness.go, test/acceptance/network_harness_builder.go
Added a test to assert that an incoming transaction trigger immediate block closure
This test fails because Lean Helix blocks the gossip goroutine
=> added a failing test for empty block time

services/gossip/adapter/tcp/direct_harness.go, services/gossip/adapter/tcp/direct_incoming.go, services/gossip/adapter/tcp/direct_incoming_test.go, services/gossip/adapter/tcp/direct_transport.go, services/gossip/adapter/tcp/direct_transport_test.go, services/gossip/adapter/test/transport_contract_test.go
A previous PR (#1232) expanded the scope of DirectTransport mutex to protect against concurrent access to the outgoing message queue by peer map (`outgoingPeerQueues`).
The current PR adds a dedicated mutex for controlling access to outgoing queues map, and re-organizes the items under each mutex in a separate struct type. the new types are `lockableOutgoingQueues` and `lockableTransportServer`.
In addition to some renaming I also removed the locking of the server mutex in some cases where I coulf not find a good reason for the lock. for instance, around calls to `connect()` (not renamed to `connectForever()` to expose the fact that it launches a listener using `GoForever()`)   
Points to notice in review:
1. Cases where I removed locking of `mutex` without replacing it with any other …
=> Refactor/Rename DirectTransport mutexes

bootstrap/gamma/deploy_native_test.go, bootstrap/gamma/development_network.go, bootstrap/gamma/e2e/ethereum_finality_test.go, bootstrap/gamma/e2e/gamma_e2e_test.go, bootstrap/gamma/e2e/harness.go, bootstrap/gamma/gamma_e2e_test.go, bootstrap/gamma/server.go, bootstrap/gamma/server_handlers.go, bootstrap/gamma/simple_transfer_test.go, bootstrap/gamma/test_kit.go, bootstrap/inmemory/network.go, bootstrap/node.go, bootstrap/node_logic.go, config/system_factory_presets.go, docker/test/docker-compose.yml, docker/test/test.sh, services/consensusalgo/leanhelixconsensus/election_trigger.go, services/crosschainconnector/ethereum/test/config.go, services/crosschainconnector/ethereum/test/external_block_timestamp_test.go, services/crosschainconnector/ethereum/test/harness.go, services/crosschainconnector/ethereum/timestampfinder/finder_algo.go, services/transactionpool/adapter/clock.go, services/transactionpool/get_transactions_for_ordering.go, services/transactionpool/init.go, services/transactionpool/service.go, services/transactionpool/test/harness.go, test.adapters.sh, test/acceptance/network_harness.go
Added a new handler to gamma, `/debug/gamma/inc-time?seconds-to-add=n`, that adds a delta to the time of subsequent blocks.
This, on conjunction with Ganache's inc-time function, should allow us to not sleep in finality-sensitive integrative tests
=> Allow gamma to modify next block time

instrumentation/metric/registry.go, services/crosschainconnector/ethereum/timestampfinder/timestamp_finder_test.go, services/gossip/adapter/tcp/direct_outgoing.go, services/gossip/adapter/tcp/direct_transport.go, services/gossip/adapter/tcp/queue.go, services/gossip/adapter/tcp/queue_test.go, services/gossip/adapter/test/transport_contract_test.go
Due to a bug in the `MetricRegistry` we missed the fact that only a single connection's outgoing metrics where being reported - because of a name collision.
This PR adds a `panic` when attempting to register a metric with a name that already exists, as well as introducing new metrics per client:
`Gossip.OutgoingConnection.Queue.Usage.[NodeAddress].Percent`
`Gossip.OutgoingConnection.SendError.[NodeAddress].Count`
`Gossip.OutgoingConnection.EnqueueErrors.[NodeAddress].Count`
where `NodeAddress` stands for a hex-encoded representation of the Node's Orbs address
=> Added new metrics per outgoing TCP connection

config/config.go, config/file_config.go, config/file_config_test.go, config/hardcoded_config.go, services/gossip/adapter/tcp/direct_harness.go, services/gossip/adapter/tcp/direct_outgoing.go, services/gossip/adapter/tcp/direct_transport.go, services/gossip/adapter/tcp/direct_transport_test.go, services/gossip/adapter/tcp/queue.go, services/gossip/adapter/test/transport_contract_test.go, test/e2e/network.go
This PR moves all code that deals with a single client connection within `DirectTransport` to a new struct, `clientConnection`. This is in preparation for a future PR to allow updating peer topology in runtime.
=> TCP Transport - client-related code moved to own struct

services/consensusalgo/leanhelixconsensus/election_trigger_test.go
Code for Lean Helix's Leader Election Trigger will soon be moved from `orbs-network-go` into `lean-helix-go`, along with its tests.
The specific test that is being skipped now is flaky because it uses timers. In addition it tests code that is obsolete and planned to be deleted once the new goroutine model in Lean Helix will be used by orbs-network-go.
=> Skip a flaky test for Lean Helix's Leader Election Trigger

bootstrap/gamma/deploy_native_test.go, services/processor/native/repository/_Deployments/deploy.go, services/processor/native/repository/_Deployments/service_name.go, services/processor/native/repository/_Deployments/service_name_test.go, services/processor/native/repository/all_system_contracts_declared_test.go
sanitization of contract names :
contract names checked before deploy that they are not system and are alphanumeric only.
also for deploy contract name is case insensitive. HOWEVER contract name is case sensitive for reading/accessing.
(example can deploy "randomName", then access it only as "randomName", but can't deploy "RANDOMNAME" as a new contract.
also added test to check all system contracts are checked as such for proper deploy
fixes #1067
fixes #571
=> sanitization of contract names 

services/blockstorage/adapter/memory/memory_persistence.go, services/gossip/dispatcher.go, services/gossip/service.go, test/acceptance/network_harness.go
- added topic size to "transport message received" message
- copying preloaded blocks on creation of memory persistence to avoid accidental sharing of blocks
=> Don't share blocks between in-memory persistence instances

services/gossip/dispatcher.go, services/gossip/service.go
Dispatcher thread is blocked when waiting for topic buffer to empty out,
this leads to deadlocks when topic A consumer thread is waiting for a gossip message to arrive on another topic B. the dispatcher is not dispatching because it's waiting for consumer of topic A to read the next message and clear the buffer, but this will never happen because topic B is now frozen since the dispatcher is deadlocked.
=> Gossip topic ignore overflowing messages 

test.flakiness.sh
We have opened a ticket with CircleCI to try and address the `Killed...` signal we are getting for our `go test` within the nightly build.
Since we have no other data to act upon at this stage, I'm proposing a reduction in go's concurrent tests iterations from 50 to a value of 30.
=> Mitigate nightly (hopefully related)

services/processor/native/call.go, services/processor/native/call_test.go
Fixes the bug when `f(1)` would fail if it was defined in the smart contract.
```golang
package main
import "fmt"
func f(a int, bs...uint) {
fmt.Println(a, bs)
}
func main() {
f(1)
}
```
=> Fix passing empty array of variable length to a contract

docker/build/Dockerfile.export, docker/build/go.mod.template, services/processor/native/adapter/native_compiler.go, test/e2e/file_utils.go, test/e2e/network.go
To reduce compilation time we download all dependencies of the contract compiler (contract sdk) when building the docker image. 
in addition, when invoking the compiler, disallow making any changes to go.mod file. if changes are required the compilation fails
=> prefetch contract compiler dependencies and prevent go.mod changes

.githooks/post-checkout, .githooks/post-merge
the hooks has some flaws. and occasionally when failures occurred it left the folders in a messed up state. which is why I'm removing it now that we require it's use less frequently - since the transition to go modules
=> disable ./git-submodule-checkout.sh in githooks

test/acceptance/memory_leak_test.go
They don't test what they pretend to (see inline), so they should either be deleted or fixed.
Presently memory is checked by running endurance test and monitoring memory usage by [project marvin](https://github.com/orbs-network/marvin). See also issue https://github.com/orbs-network/orbs-network-go/issues/1346
=> Skip memory leak tests

services/gossip/adapter/testkit/tamperers.go, services/gossip/adapter/transport.go
Fixes #1357 
* Removed unused struct `ErrCorruptData`
* Renamed `ErrTransportFailed` to `messageDroppedByTamperer` and moved into tamperers.go
* Modified wording in `messageDroppedByTamperer.Error()`
=> Failing Tamperer Transport - error message not clear when failing Send() intentionally

services/blockstorage/internodesync/harness.go
Fixes: #1332 
Increase EventuallyVerify test timeout for message receival from 10m to 50ms (possible cause of flakiness)
=> Increase test timeout for message receival 

synchronization/trigger.go, synchronization/trigger_test.go
See #1339 for flakiness in `TestPeriodicalTriggerKeepsGoingOnPanic` 
additionally noticed similar flakiness in `TestPeriodicalTriggerStartsOk`.
This PR addresses both issues
=> Resolve flakiness in trigger_test.go

bootstrap/gamma/server.go, bootstrap/httpserver/server.go, bootstrap/httpserver/server_handlers_test.go, bootstrap/node.go
fixes #1371 
This will make the HTTP server launch immediately and serve non public-api endpoints (metrics, robots.txt, etc) while the node is initializing.
=> Serve HTTP requests early

services/crosschainconnector/ethereum/test/external_block_timestamp_test.go, services/crosschainconnector/ethereum/test/get_transaction_logs_test.go
An unexpected delay between contract deployment and padding with blocks for finality can cause a failure:
```
Blk# | Time
369  | 66      start                <-   returned block - too early
370  | 67      deploy               <-   block at augmented reference
| 68      (unexpceted delay)   <-   augmented reference
371  | 69      pad                  <-   reference = startTime + 3
372  | 70      pad
```
This changes the reference time to that of the most recent padding block.
=> Fix flakiness of TestFullFlowWithVaryingTimestamps

bootstrap/gamma/ethereum/ethereum_finality_test.go, bootstrap/gamma/harness.go
At some point there is a query immediately following a transaction. In one of my executions the query failed because it ran on a node that wasn't synced with the transaction.
This will poll on the query result to assure that the block height is at least as high as that of the transaction.
Will poll for no longer than 10 seconds.
=> Fix flakiness of TestReadFromEthereumLogsTakingFinalityIntoAccount

services/blockstorage/adapter/filesystem/codec.go, services/blockstorage/adapter/filesystem/construct_index_test.go, services/blockstorage/adapter/filesystem/file_system_persistence.go, test/builders/random_blocks.go
This uses a buffered reader for more efficient reading of blocks from the disk.
Currently the buffer size is 1MB, which on my machine decreased the block indexing time for the 5GB block file from production from ~75 seconds to ~10 seconds.
also, resolved #1385
=> Speed up block indexing by buffering reads

test/e2e/deploy_native_test.go
this would allow us to remove the same test in `gamma-cli` which I think doesn't belong there.
Notwithstanding the fact that we need to understand we it failed there.
=> duplicate deployment test in e2e

services/processor/native/sanitize_code.go
(needed to support use of big.Int in contracts.
=> add math/big to white list for orbs contracts

test/acceptance/network_harness.go, test/acceptance/stress_test.go
To resolve flakiness of the test
=> Increase timeout of TestGazillionTxWhileDroppingMessage to 1 minute

test/e2e/deploy_experimental_test.go, test/e2e/harness.go
RunQuery returns an error when the contract is not deployed. This will suppress the error when polling for the correct block height. If polling is unsuccessful the last error will be returned.
Another related fix - when submitting a transaction synchronously, the SDK treats HTTP 202 (indicating the transaction is still pending) as an error. Added this as an exception in the test flow.
=> Fix race with query immediately following contract deployment

services/processor/native/adapter/native_compiler.go, services/processor/native/adapter/race_build_flag_norace.go, services/processor/native/adapter/race_build_flag_withrace.go, test/e2e/deploy_experimental_test.go, test/e2e/deploy_native_test.go, test/e2e/deploy_native_whitelist_test.go
Fixes #1432 
To support running E2E tests with race detection.
=> Add -race to the native compiler's build command when running with race

services/consensusalgo/benchmarkconsensus/common.go, services/consensusalgo/benchmarkconsensus/leader.go, services/consensusalgo/benchmarkconsensus/non_leader.go
There is a race when a node is updated with a new block concurrently through block sync and consensus. The consensus block sync handler will attempt to update the last committed block, but will find that the it doesn't match the current block and return with an error. Block sync in return will output an error to the log, and tests fail.
The solution suggested here is to not treat this as an error - it is a valid flow. Instead, add an info log and ignore.
=> Fix benchmark consensus sync race

.circleci/config.yml, .circleci/marvin-stress.sh
=> Issue 1454: Update marvin dependencies in CircleCI; change its timing

.circleci/config.yml
As they are redundant given benchmark consensus is tested on acceptance tests, and that we also run with LH.
=> Remove tests with benchmark consensus from e2e

test/_manual/memory_leak_test.go, test/acceptance/api_responses_test.go, test/acceptance/committee_election_test.go, test/acceptance/consensus_test.go, test/acceptance/deploy_native_test.go, test/acceptance/duplicate_tx_test.go, test/acceptance/empty_block_time_test.go, test/acceptance/lean_helix_recovers_from_disk_error_test.go, test/acceptance/network_benchmark_test.go, test/acceptance/network_harness.go, test/acceptance/node_sync_test.go, test/acceptance/quorum_size_test.go, test/acceptance/sanity_test.go, test/acceptance/service_sync_test.go, test/acceptance/simple_transfer_test.go, test/acceptance/stress_benchmark_test.go, test/acceptance/stress_test.go, test/acceptance/stress_test_harness_all.go, test/acceptance/stress_test_harness_memoryleak.go, test/acceptance/subscription_state_test.go, test/acceptance/trigger_test.go
resolves #549 
An old bug dealing with manual tests failing compilation and execution - caused by tests marked to be excluded from compilation, and then a commit that broke them caused the IDE to never parse this file. Over time the harness was refactored and the distance between the code and framework gradually grew.
The tests pass now and hopefully IDE will include the file in future refactoring so the compilation will not break again. Consider removing the `_` from the folder name `_manual` and adding `t.Skip()` commands to ensure compilation and no execution when running `go test ...` @electricmonk  what do you think?
=> manual memory leak test - fixed

services/gossip/adapter/tcp/outgoing_connection.go
Gad wants to measure latency per connection to be able to tweak LH timings.
@IdoZilberberg can you please advise if this is good enough for Kibana?
=> Add metrics for connection latency per node (requested by @gadcl)

services/gossip/topic_lean_helix.go
Prevents Gossip from broadcasting messages when multicast was requested. 
This fix will prevent view change messages from begin delivered to all nodes rather than only to the leader.
=> don't broadcast lh messages arbitrarily

go.sum, services/consensuscontext/call_contract_elected_validators.go, services/consensuscontext/call_contract_ordered_committee.go
Some system contract calls retry until success, and report every 500th failure (including the first) by logging an error. 
There is a reoccurring CircleCI issue (#1443) where test containers freeze for a period of 300ms-1s, causing the first attempt to fail on "timeout". The error log then fails the tests. 
Since this issue only manifests itself this way, switching from error log to warning (info-error) seems like a decent workaround.
The info-error logs are still shipped to logzio, but will not fail tests.
=> System contract retries - log warning instead of error

test.common.sh
running test.sh locally would not bring meaningful output due to missing tac command on Darwin based systems. 
BSD-style system have most functionality of `tac` covered by `tail -r`
This PR deals with checking whether we are running on a Mac OS system and if so sets up a local function inside our test.common bash library for testing so that the system can have access to a similar `tac` functionality.
=> Adding tac-like functionality for Mac OS based system so that test.sh would work

services/statestorage/adapter/memory/memory_persistence.go, services/statestorage/service.go, services/statestorage/service_test.go
The nature of the leak is that any block that contained the state diff was held up in memory because the state diffs were referencing the underlying byte array.
After applying the fix, testing on 3.9Gb blocks file for vchain 1960000 revealed that allocated memory after starting up went down from `878mb` to `478mb` which is `45.5%` improvement.
This PR partially resolves #1520
=> Fix state storage memory leak

services/statestorage/adapter/memory/memory_persistence.go, services/statestorage/adapter/memory/memory_persistence_test.go, services/statestorage/adapter/persistence.go, services/statestorage/rolling_revisions.go, services/statestorage/rolling_revisions_test.go, services/statestorage/service.go, services/statestorage/service_test.go
Instead of passing the struct around, @jlevison fix references key and value directly, reducing memory footprint by `8%` (tested on `3.9Gb` blocks file).
=> Removing extra structs/pointers from state storage

services/consensuscontext/call_contract_ordered_committee.go, services/processor/native/repository/Committee/committee.go, services/processor/native/repository/Committee/committee_test.go, services/processor/native/repository/Committee/index.go, services/processor/native/repository/Committee/reputation.go, services/processor/native/repository/Committee/reputation_test.go
New algo to calculate reputation :
1) rep is now 0-6, (instead of 4-10) and rep 1 indicates a slash of half your chance to be leader.
2) algo is based on weighted draw
3) getAllX doesn't represent a committee order anymore.
4) input is assumed in consensus order so that the genesis has to first sort its config node addresses
=> new reputation calculation with a weighted non-repeated draw

go.mod, services/blockstorage/block_sync_server.go, services/blockstorage/test/block_sync_server_test.go, services/gossip/adapter/tcp/queue.go, services/gossip/topic_block_sync.go
In case of an error arising form the block chunk being too big, the block-sync server will retry sending the blocks with smaller and smaller chunk sizes (diving by 2 each time).
Fixes #1514
=> Block sync - retry with smaller chunk sizes 

.circleci/config.yml, .circleci/release-node-to-staging.sh
Releases any node version to `orbsnetworkstaging/node` docker repo.
=> Release to dockerhub staging

bootstrap/node.go
Was mistakenly removed in #1551
=> Fix regression: missing node address metric

services/management/adapter/file_provider.go, services/management/adapter/file_provider_test.go
There were couple of issues:
1. we don't need to validate the IP because the file might use hostnames and it's also valid
2. the error was not thrown in some places because it was `nil`
So I have removed excessive validation and replaced `errors.Wrapf` with `errors.Errorf` where needed.
=> Remove IP validation from vc topology

services/management/adapter/file_provider.go, services/management/adapter/file_provider_test.go
fixes #1582 
Historic response (timestamp given):
start <= end <= current
Latest response (no timestamp given):
start <= end = current
check weights are not 0
=> Fix missing checks in file provider of weights and current ref time

bootstrap/node.go
when we don't really use it (after removal of eth endpoint from config and use of default-fake-one)
=> disable status update of eth conn 

entrypoint.sh
- remove redundant log file processor `tai64nlocal`
- increase the maximal logs retention to 0.5Gb
=> retain 0.5Gb of logs

instrumentation/metric/registry.go, instrumentation/metric/registry_test.go, services/gossip/adapter/tcp/outgoing_connection.go, services/gossip/adapter/tcp/queue.go
registry work with names not pointer (except remove that checks same object), try and remove metric from outgoing_connection.go and queue.go before creating new one to avoid "double register"
=> Registry metric double name fix, clean up outgoing cons metrics

go.mod, services/blockstorage/init.go, services/consensusalgo/leanhelixconsensus/block_provider.go, services/consensuscontext/committee.go
includes renaming consensusContext.ValidateBlockCommittee -> ValidateBlockReferenceTime  + lean-helix latest version (includes soft validation and reduce incoming msgs logging) + includes metric fix for vc stuck
=> updated the go-mod to include orbs-spec latest version and lean-helix v0.6.1 version

go.mod, services/blockstorage/init.go
fix to LastCommit.Time metric initial value (now) overridden by 0 
updated the go-mod to lean-helix latest tag v0.6.2
=> fix vc-stuck metric 

config/config_component_tests_presets.go, config/config_interfaces.go, services/blockstorage/internodesync/block_sync.go, services/blockstorage/internodesync/state_processing_blocks.go, services/consensuscontext/committee.go, services/consensuscontext/test/validate_block_test.go
fix to config.CommitteeGraceTime used in consensusContext on ValidateBlockRefTime during sync (verify chain tip)
=> fix sync config used in consensusContext
